Dataset nÂº  39
Shape: (294, 14)(examples, features)
Traceback (most recent call last):
  File "runClassifier.py", line 122, in <module>
    model = model.fit(Datasets, TargetNames)
  File "/home/core/Documents/PedroAlves/autoBagging/autoBaggingClassifier.py", line 94, in fit
    meta_features_estematic = self._metafeatures(
  File "/home/core/Documents/PedroAlves/autoBagging/autoBaggingClassifier.py", line 381, in _metafeatures
    metafeatures_values, metafeatures_names = metafeature_generator(
  File "/home/core/Documents/PedroAlves/autoBagging/metafeatures/core/engine.py", line 6, in metafeature_generator
    data_numpy, attributes = analyze_pd_dataframe(data, target)
  File "/home/core/Documents/PedroAlves/autoBagging/metafeatures/core/object_analyzer.py", line 49, in analyze_pd_dataframe
    dataframe = _replace_objects_by_integers(dataframe, attribute_types)
  File "/home/core/Documents/PedroAlves/autoBagging/metafeatures/core/object_analyzer.py", line 125, in _replace_objects_by_integers
    dataframe.loc[:, column_name] = series
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/indexing.py", line 540, in _setitem_with_indexer
    setter(labels[0], value)
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/indexing.py", line 490, in setter
    s._data = s._data.setitem(indexer=pi, value=v)
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 560, in setitem
    return self.apply("setitem", **kwargs)
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1837, in setitem
    self.values[indexer] = value
  File "/home/core/anaconda3/envs/PedroAlves/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 2189, in __setitem__
    raise ValueError(
ValueError: Cannot setitem on a Categorical with a new category, set the categories first

